spirit_island_database:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: 'database'
      schema: 'main'
      schemas_and_paths:
        main: '/home/samuel-hutchinson/spirit-island.db'
      schema_directory: '/home/samuel-hutchinson/'
      #optional fields
      # extensions:
      #   - "/path/to/sqlean/crypto.so"